### PR TITLE
Replace Set to Dictionary

### PR DESCRIPTION
**Pull request by XWJACK**

### CODE REVIEW

**Comment by nixzhu** [comment]
Replace Set with Dictionary is a good idea. But, we do need `removeListenerWithName` for fine-grained control.

**Comment by XWJACK** [comment]
what about this?
```swift
public func removeListenerWithName(_ name: String) {
        listenerts[name] = nil
    }
```

**Comment by nixzhu** [comment]
It's OK. You need to do test before send a PR, make sure it works.
Usually, if a PR just change the way to code but not with any improvement, it will be rejected.

**Comment by XWJACK** [comment]
I forgot to test before PR.😂

**Pull request closed without merging**
